[package]
name = "restaurant_app_assignment"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "^0.7.7"
tower = "^0.5.1"
serde = { version = "^1.0.210", features = ["derive"] }
tokio-postgres = "^0.7.12"
