services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 58000:8000
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_app
    ports:
      - 55432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
